const countryDictionary = {
  afghanistan: 'Afghanistan',
  albania: 'Albania',
  algeria: 'Algeria',
  andorra: 'Andorra',
  angola: 'Angola',
  anguilla: 'Anguilla',
  'antigua-and-barbuda': 'Antigua and Barbuda',
  argentina: 'Argentina',
  armenia: 'Armenia',
  aruba: 'Aruba',
  australia: 'Australia',
  austria: 'Austria',
  azerbaijan: 'Azerbaijan',
  bahamas: 'Bahamas',
  bahrain: 'Bahrain',
  bangladesh: 'Bangladesh',
  barbados: 'Barbados',
  belarus: 'Belarus',
  belgium: 'Belgium',
  belize: 'Belize',
  benin: 'Benin',
  bermuda: 'Bermuda',
  bhutan: 'Bhutan',
  bolivia: 'Bolivia',
  bosnia: 'Bosnia',
  botswana: 'Botswana',
  brazil: 'Brazil',
  'british-virgin-islands': 'British Virgin Islands',
  brunei: 'Brunei',
  bulgaria: 'Bulgaria',
  'burkina-faso': 'Burkina Faso',
  burundi: 'Burundi',
  'cabo-verde': 'Cabo Verde',
  cambodia: 'Cambodia',
  cameroon: 'Cameroon',
  canada: 'Canada',
  'caribbean-netherlands': 'Caribbean Netherlands',
  'cayman-islands': 'Cayman Islands',
  'central-african-republic': 'Central African Republic',
  chad: 'Chad',
  'channel-islands': 'Channel Islands',
  chile: 'Chile',
  china: 'China',
  colombia: 'Colombia',
  comoros: 'Comoros',
  congo: 'Congo',
  'costa-rica': 'Costa Rica',
  croatia: 'Croatia',
  cuba: 'Cuba',
  curacao: 'Curaçao',
  cyprus: 'Cyprus',
  czechia: 'Czechia',
  'cote-d-ivoire': "Côte d'Ivoire",
  drc: 'DRC',
  denmark: 'Denmark',
  djibouti: 'Djibouti',
  dominica: 'Dominica',
  'dominican-republic': 'Dominican Republic',
  ecuador: 'Ecuador',
  egypt: 'Egypt',
  'el-salvador': 'El Salvador',
  'equatorial-guinea': 'Equatorial Guinea',
  eritrea: 'Eritrea',
  estonia: 'Estonia',
  ethiopia: 'Ethiopia',
  'falkland-islands-malvinas': 'Falkland Islands (Malvinas)',
  'faroe-islands': 'Faroe Islands',
  fiji: 'Fiji',
  finland: 'Finland',
  france: 'France',
  'french-guiana': 'French Guiana',
  'french-polynesia': 'French Polynesia',
  gabon: 'Gabon',
  gambia: 'Gambia',
  georgia: 'Georgia',
  germany: 'Germany',
  ghana: 'Ghana',
  gibraltar: 'Gibraltar',
  greece: 'Greece',
  greenland: 'Greenland',
  grenada: 'Grenada',
  guadeloupe: 'Guadeloupe',
  guatemala: 'Guatemala',
  guinea: 'Guinea',
  'guinea-bissau': 'Guinea-Bissau',
  guyana: 'Guyana',
  haiti: 'Haiti',
  'holy-see-vatican-city-state': 'Holy See (Vatican City State)',
  honduras: 'Honduras',
  'hong-kong': 'Hong Kong',
  hungary: 'Hungary',
  iceland: 'Iceland',
  india: 'India',
  indonesia: 'Indonesia',
  iran: 'Iran',
  iraq: 'Iraq',
  ireland: 'Ireland',
  'isle-of-man': 'Isle of Man',
  israel: 'Israel',
  italy: 'Italy',
  jamaica: 'Jamaica',
  japan: 'Japan',
  jordan: 'Jordan',
  kazakhstan: 'Kazakhstan',
  kenya: 'Kenya',
  kuwait: 'Kuwait',
  kyrgyzstan: 'Kyrgyzstan',
  'lao-people-s-democratic-republic': "Lao People's Democratic Republic",
  latvia: 'Latvia',
  lebanon: 'Lebanon',
  lesotho: 'Lesotho',
  liberia: 'Liberia',
  'libyan-arab-jamahiriya': 'Libyan Arab Jamahiriya',
  liechtenstein: 'Liechtenstein',
  lithuania: 'Lithuania',
  luxembourg: 'Luxembourg',
  macao: 'Macao',
  macedonia: 'Macedonia',
  madagascar: 'Madagascar',
  malawi: 'Malawi',
  malaysia: 'Malaysia',
  maldives: 'Maldives',
  mali: 'Mali',
  malta: 'Malta',
  martinique: 'Martinique',
  mauritania: 'Mauritania',
  mauritius: 'Mauritius',
  mayotte: 'Mayotte',
  mexico: 'Mexico',
  moldova: 'Moldova',
  monaco: 'Monaco',
  mongolia: 'Mongolia',
  montenegro: 'Montenegro',
  montserrat: 'Montserrat',
  morocco: 'Morocco',
  mozambique: 'Mozambique',
  myanmar: 'Myanmar',
  namibia: 'Namibia',
  nepal: 'Nepal',
  netherlands: 'Netherlands',
  'new-caledonia': 'New Caledonia',
  'new-zealand': 'New Zealand',
  nicaragua: 'Nicaragua',
  niger: 'Niger',
  nigeria: 'Nigeria',
  norway: 'Norway',
  oman: 'Oman',
  pakistan: 'Pakistan',
  palestine: 'Palestine',
  panama: 'Panama',
  'papua-new-guinea': 'Papua New Guinea',
  paraguay: 'Paraguay',
  peru: 'Peru',
  philippines: 'Philippines',
  poland: 'Poland',
  portugal: 'Portugal',
  qatar: 'Qatar',
  romania: 'Romania',
  russia: 'Russia',
  rwanda: 'Rwanda',
  reunion: 'Réunion',
  's-korea': 'S. Korea',
  'saint-kitts-and-nevis': 'Saint Kitts and Nevis',
  'saint-lucia': 'Saint Lucia',
  'saint-martin': 'Saint Martin',
  'saint-pierre-miquelon': 'Saint Pierre Miquelon',
  'saint-vincent-and-the-grenadines': 'Saint Vincent and the Grenadines',
  'san-marino': 'San Marino',
  'sao-tome-and-principe': 'Sao Tome and Principe',
  'saudi-arabia': 'Saudi Arabia',
  senegal: 'Senegal',
  serbia: 'Serbia',
  seychelles: 'Seychelles',
  'sierra-leone': 'Sierra Leone',
  singapore: 'Singapore',
  'sint-maarten': 'Sint Maarten',
  slovakia: 'Slovakia',
  slovenia: 'Slovenia',
  somalia: 'Somalia',
  'south-africa': 'South Africa',
  'south-sudan': 'South Sudan',
  spain: 'Spain',
  'sri-lanka': 'Sri Lanka',
  'st-barth': 'St. Barth',
  sudan: 'Sudan',
  suriname: 'Suriname',
  swaziland: 'Swaziland',
  sweden: 'Sweden',
  switzerland: 'Switzerland',
  'syrian-arab-republic': 'Syrian Arab Republic',
  taiwan: 'Taiwan',
  tajikistan: 'Tajikistan',
  tanzania: 'Tanzania',
  thailand: 'Thailand',
  'timor-leste': 'Timor-Leste',
  togo: 'Togo',
  'trinidad-and-tobago': 'Trinidad and Tobago',
  tunisia: 'Tunisia',
  turkey: 'Turkey',
  'turks-and-caicos-islands': 'Turks and Caicos Islands',
  uae: 'UAE',
  uk: 'UK',
  usa: 'USA',
  uganda: 'Uganda',
  ukraine: 'Ukraine',
  uruguay: 'Uruguay',
  uzbekistan: 'Uzbekistan',
  venezuela: 'Venezuela',
  vietnam: 'Vietnam',
  'western-sahara': 'Western Sahara',
  yemen: 'Yemen',
  zambia: 'Zambia',
  zimbabwe: 'Zimbabwe',
};

const countryOptions = Object.entries(countryDictionary).map(
  ([slug, country]) => ({
    value: slug,
    label: country,
  })
);

function findCountry(slug) {
  const countryName = countryDictionary[slug];

  if (countryName) {
    return { name: countryName, slug };
  }
}

export { findCountry, countryOptions };
