const countryList = [
  'USA',
  'Brazil',
  'India',
  'Russia',
  'South Africa',
  'Peru',
  'Mexico',
  'Colombia',
  'Chile',
  'Spain',
  'Iran',
  'UK',
  'Saudi Arabia',
  'Argentina',
  'Pakistan',
  'Bangladesh',
  'Italy',
  'Turkey',
  'Germany',
  'France',
  'Iraq',
  'Philippines',
  'Indonesia',
  'Canada',
  'Qatar',
  'Kazakhstan',
  'Ecuador',
  'Bolivia',
  'Egypt',
  'Israel',
  'Ukraine',
  'Dominican Republic',
  'China',
  'Sweden',
  'Oman',
  'Panama',
  'Belgium',
  'Kuwait',
  'Romania',
  'Belarus',
  'UAE',
  'Netherlands',
  'Guatemala',
  'Poland',
  'Singapore',
  'Portugal',
  'Japan',
  'Honduras',
  'Nigeria',
  'Bahrain',
  'Ghana',
  'Kyrgyzstan',
  'Armenia',
  'Morocco',
  'Algeria',
  'Switzerland',
  'Afghanistan',
  'Uzbekistan',
  'Azerbaijan',
  'Venezuela',
  'Moldova',
  'Kenya',
  'Serbia',
  'Ethiopia',
  'Costa Rica',
  'Ireland',
  'Nepal',
  'Australia',
  'Austria',
  'El Salvador',
  'Czechia',
  'Cameroon',
  "Côte d'Ivoire",
  'Palestine',
  'Bosnia',
  'Denmark',
  'S. Korea',
  'Bulgaria',
  'Madagascar',
  'Macedonia',
  'Sudan',
  'Senegal',
  'Norway',
  'DRC',
  'Paraguay',
  'Zambia',
  'Malaysia',
  'French Guiana',
  'Lebanon',
  'Guinea',
  'Gabon',
  'Tajikistan',
  'Haiti',
  'Libyan Arab Jamahiriya',
  'Finland',
  'Luxembourg',
  'Albania',
  'Greece',
  'Mauritania',
  'Croatia',
  'Maldives',
  'Djibouti',
  'Zimbabwe',
  'Malawi',
  'Hungary',
  'Equatorial Guinea',
  'Central African Republic',
  'Hong Kong',
  'Nicaragua',
  'Montenegro',
  'Namibia',
  'Congo',
  'Swaziland',
  'Thailand',
  'Cuba',
  'Somalia',
  'Cabo Verde',
  'Mayotte',
  'Suriname',
  'Sri Lanka',
  'Slovakia',
  'Mozambique',
  'Mali',
  'South Sudan',
  'Slovenia',
  'Lithuania',
  'Rwanda',
  'Estonia',
  'Guinea-Bissau',
  'Benin',
  'Tunisia',
  'Iceland',
  'Sierra Leone',
  'Angola',
  'Yemen',
  'Gambia',
  'New Zealand',
  'Syrian Arab Republic',
  'Uganda',
  'Uruguay',
  'Malta',
  'Jordan',
  'Cyprus',
  'Georgia',
  'Latvia',
  'Liberia',
  'Bahamas',
  'Burkina Faso',
  'Botswana',
  'Niger',
  'Togo',
  'Jamaica',
  'Aruba',
  'Andorra',
  'Chad',
  'Vietnam',
  'Lesotho',
  'Sao Tome and Principe',
  'Réunion',
  'San Marino',
  'Guyana',
  'Channel Islands',
  'Tanzania',
  'Trinidad and Tobago',
  'Taiwan',
  'Guadeloupe',
  'Burundi',
  'Comoros',
  'Belize',
  'Myanmar',
  'Faroe Islands',
  'Mauritius',
  'Isle of Man',
  'Martinique',
  'Sint Maarten',
  'Mongolia',
  'Turks and Caicos Islands',
  'Eritrea',
  'Cambodia',
  'Papua New Guinea',
  'Gibraltar',
  'Cayman Islands',
  'French Polynesia',
  'Bermuda',
  'Barbados',
  'Monaco',
  'Brunei',
  'Bhutan',
  'Seychelles',
  'Saint Martin',
  'Antigua and Barbuda',
  'Liechtenstein',
  'Saint Vincent and the Grenadines',
  'Macao',
  'Curaçao',
  'Fiji',
  'Saint Lucia',
  'Timor-Leste',
  'Grenada',
  'New Caledonia',
  "Lao People's Democratic Republic",
  'Dominica',
  'Saint Kitts and Nevis',
  'Greenland',
  'Caribbean Netherlands',
  'Falkland Islands (Malvinas)',
  'Montserrat',
  'St. Barth',
  'Holy See (Vatican City State)',
  'Western Sahara',
  'British Virgin Islands',
  'Saint Pierre Miquelon',
  'Anguilla',
].sort();

const countryOptions = countryList.map((country) => ({
  value: country,
  label: country,
}));

export { countryList, countryOptions };
